#pragma once
#include <nlohmann/json.hpp>

namespace N2Engine::Input
{
    enum class Key
    {
        Unknown = 0,
        Space,
        Apostrophe,
        Comma,
        Minus,
        Period,
        Slash,
        Key0,
        Key1,
        Key2,
        Key3,
        Key4,
        Key5,
        Key6,
        Key7,
        Key8,
        Key9,
        Semicolon,
        Equal,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftBracket,
        Backslash,
        RightBracket,
        GraveAccent,
        Escape,
        Enter,
        Tab,
        Backspace,
        Insert,
        Delete,
        Right,
        Left,
        Down,
        Up,
        PageUp,
        PageDown,
        Home,
        End,
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        Kp0,
        Kp1,
        Kp2,
        Kp3,
        Kp4,
        Kp5,
        Kp6,
        Kp7,
        Kp8,
        Kp9,
        KpDecimal,
        KpDivide,
        KpMultiply,
        KpSubtract,
        KpAdd,
        KpEnter,
        KpEqual,
        LeftShift,
        LeftControl,
        LeftAlt,
        LeftSuper,
        RightShift,
        RightControl,
        RightAlt,
        RightSuper,
        Menu
    };

    NLOHMANN_JSON_SERIALIZE_ENUM(Key, {
        {Key::Unknown, "Unknown"},
        {Key::Space, "Space"},
        {Key::Apostrophe, "Apostrophe"},
        {Key::Comma, "Comma"},
        {Key::Minus, "Minus"},
        {Key::Period, "Period"},
        {Key::Slash, "Slash"},
        {Key::Key0, "Key0"},
        {Key::Key1, "Key1"},
        {Key::Key2, "Key2"},
        {Key::Key3, "Key3"},
        {Key::Key4, "Key4"},
        {Key::Key5, "Key5"},
        {Key::Key6, "Key6"},
        {Key::Key7, "Key7"},
        {Key::Key8, "Key8"},
        {Key::Key9, "Key9"},
        {Key::Semicolon, "Semicolon"},
        {Key::Equal, "Equal"},
        {Key::A, "A"},
        {Key::B, "B"},
        {Key::C, "C"},
        {Key::D, "D"},
        {Key::E, "E"},
        {Key::F, "F"},
        {Key::G, "G"},
        {Key::H, "H"},
        {Key::I, "I"},
        {Key::J, "J"},
        {Key::K, "K"},
        {Key::L, "L"},
        {Key::M, "M"},
        {Key::N, "N"},
        {Key::O, "O"},
        {Key::P, "P"},
        {Key::Q, "Q"},
        {Key::R, "R"},
        {Key::S, "S"},
        {Key::T, "T"},
        {Key::U, "U"},
        {Key::V, "V"},
        {Key::W, "W"},
        {Key::X, "X"},
        {Key::Y, "Y"},
        {Key::Z, "Z"},
        {Key::LeftBracket, "LeftBracket"},
        {Key::Backslash, "Backslash"},
        {Key::RightBracket, "RightBracket"},
        {Key::GraveAccent, "GraveAccent"},
        {Key::Escape, "Escape"},
        {Key::Enter, "Enter"},
        {Key::Tab, "Tab"},
        {Key::Backspace, "Backspace"},
        {Key::Insert, "Insert"},
        {Key::Delete, "Delete"},
        {Key::Right, "Right"},
        {Key::Left, "Left"},
        {Key::Down, "Down"},
        {Key::Up, "Up"},
        {Key::PageUp, "PageUp"},
        {Key::PageDown, "PageDown"},
        {Key::Home, "Home"},
        {Key::End, "End"},
        {Key::CapsLock, "CapsLock"},
        {Key::ScrollLock, "ScrollLock"},
        {Key::NumLock, "NumLock"},
        {Key::PrintScreen, "PrintScreen"},
        {Key::Pause, "Pause"},
        {Key::F1, "F1"},
        {Key::F2, "F2"},
        {Key::F3, "F3"},
        {Key::F4, "F4"},
        {Key::F5, "F5"},
        {Key::F6, "F6"},
        {Key::F7, "F7"},
        {Key::F8, "F8"},
        {Key::F9, "F9"},
        {Key::F10, "F10"},
        {Key::F11, "F11"},
        {Key::F12, "F12"},
        {Key::Kp0, "Kp0"},
        {Key::Kp1, "Kp1"},
        {Key::Kp2, "Kp2"},
        {Key::Kp3, "Kp3"},
        {Key::Kp4, "Kp4"},
        {Key::Kp5, "Kp5"},
        {Key::Kp6, "Kp6"},
        {Key::Kp7, "Kp7"},
        {Key::Kp8, "Kp8"},
        {Key::Kp9, "Kp9"},
        {Key::KpDecimal, "KpDecimal"},
        {Key::KpDivide, "KpDivide"},
        {Key::KpMultiply, "KpMultiply"},
        {Key::KpSubtract, "KpSubtract"},
        {Key::KpAdd, "KpAdd"},
        {Key::KpEnter, "KpEnter"},
        {Key::KpEqual, "KpEqual"},
        {Key::LeftShift, "LeftShift"},
        {Key::LeftControl, "LeftControl"},
        {Key::LeftAlt, "LeftAlt"},
        {Key::LeftSuper, "LeftSuper"},
        {Key::RightShift, "RightShift"},
        {Key::RightControl, "RightControl"},
        {Key::RightAlt, "RightAlt"},
        {Key::RightSuper, "RightSuper"},
        {Key::Menu, "Menu"}
    })

    enum class GamepadButton
    {
        South,
        East,
        West,
        North,
        LeftBumper,
        RightBumper,
        Back,
        Start,
        Guide,
        LeftThumb,
        RightThumb,
        DpadUp,
        DpadRight,
        DpadDown,
        DpadLeft
    };

    NLOHMANN_JSON_SERIALIZE_ENUM(GamepadButton, {
        {GamepadButton::South, "South"},
        {GamepadButton::East, "East"},
        {GamepadButton::West, "West"},
        {GamepadButton::North, "North"},
        {GamepadButton::LeftBumper, "LeftBumper"},
        {GamepadButton::RightBumper, "RightBumper"},
        {GamepadButton::Back, "Back"},
        {GamepadButton::Start, "Start"},
        {GamepadButton::Guide, "Guide"},
        {GamepadButton::LeftThumb, "LeftThumb"},
        {GamepadButton::RightThumb, "RightThumb"},
        {GamepadButton::DpadUp, "DpadUp"},
        {GamepadButton::DpadRight, "DpadRight"},
        {GamepadButton::DpadDown, "DpadDown"},
        {GamepadButton::DpadLeft, "DpadLeft"}
    })

    enum class GamepadAxis
    {
        LeftX,
        LeftY,
        RightX,
        RightY,
        LeftTrigger,
        RightTrigger
    };

    NLOHMANN_JSON_SERIALIZE_ENUM(GamepadAxis, {
        {GamepadAxis::LeftX, "LeftX"},
        {GamepadAxis::LeftY, "LeftY"},
        {GamepadAxis::RightX, "RightX"},
        {GamepadAxis::RightY, "RightY"},
        {GamepadAxis::LeftTrigger, "LeftTrigger"},
        {GamepadAxis::RightTrigger, "RightTrigger"}
    })

    enum class MouseButton
    {
        Left,
        Right,
        Middle,
        Button4,
        Button5,
        Button6,
        Button7,
        Button8
    };

    NLOHMANN_JSON_SERIALIZE_ENUM(MouseButton, {
        {MouseButton::Left, "Left"},
        {MouseButton::Right, "Right"},
        {MouseButton::Middle, "Middle"},
        {MouseButton::Button4, "Button4"},
        {MouseButton::Button5, "Button5"},
        {MouseButton::Button6, "Button6"},
        {MouseButton::Button7, "Button7"},
        {MouseButton::Button8, "Button8"}
    })

    enum class BindingType
    {
        KeyboardButton,
        GamepadButton,
        GamepadAxis,
        GamepadStick,
        Vector2Composite,
        MouseButton
    };

    NLOHMANN_JSON_SERIALIZE_ENUM(BindingType, {
        {BindingType::KeyboardButton, "KeyboardButton"},
        {BindingType::GamepadButton, "GamepadButton"},
        {BindingType::GamepadAxis, "GamepadAxis"},
        {BindingType::GamepadStick, "GamepadStick"},
        {BindingType::Vector2Composite, "Vector2Composite"},
        {BindingType::MouseButton, "MouseButton"}
    })
}