#include "engine/scripting/LuaScriptTemplate.hpp"

namespace N2Engine::Scripting
{
    namespace
    {
        bool IsAsciiAlphanumeric(const char c)
        {
            return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9');
        }

        constexpr std::string_view Template = R"(
-- {C} Script
-- Auto-generated by N2Engine Editor

local {C} = {}
{C}.__index = {C}

-- Serializable fields that appear in the inspector
{C}.SerializableFields = {
    speed = { type = "float", default = 5.0 },
    enabled = { type = "bool", default = true },
    -- Reference fields
    -- target = { type = "GameObject", default = nil },
    -- rigidBody = { type = "RigidBodyComponent", default = nil },
}

function {C}:OnAttach()
    -- Initialize component here
end

function {C}:OnUpdate()
    -- Update logic here
end

function {C}:OnFixedUpdate()
    -- Physics update logic here
end

function {C}:OnDestroy()
    -- Cleanup here
end

return {C}
)";
    }

    std::string LuaScriptClassName(const std::string_view scriptName)
    {
        std::string className(scriptName.substr(0, scriptName.find('.')));
        for (char &c : className)
        {
            if (!IsAsciiAlphanumeric(c))
            {
                c = '_';
            }
        }
        if (className.empty())
        {
            return "Script";
        }
        if (className[0] >= 'a' && className[0] <= 'z')
        {
            className[0] = static_cast<char>(className[0] - 'a' + 'A');
        }
        // A Lua name can't start with a digit ("2d_player" -> "_2d_player")
        if (className[0] >= '0' && className[0] <= '9')
        {
            className.insert(className.begin(), '_');
        }
        return className;
    }

    std::string MakeLuaScriptTemplate(const std::string_view scriptName)
    {
        const std::string className = LuaScriptClassName(scriptName);
        std::string text(Template);
        size_t position = 0;
        while ((position = text.find("{C}", position)) != std::string::npos)
        {
            text.replace(position, 3, className);
            position += className.size();
        }
        return text;
    }
}
